---
version: "3.6"

networks:
  bumper:
    internal: true
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1

services:
  nginx:
    depends_on:
      - bumper
    image: nginx:alpine
    networks:
      custom_net:
        ipv4_address: 192.168.1.14
      bumper:
    ports:
      - 443:443
      - 5223:5223
      - 8007:8007
      - 8883:8883
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/:/etc/nginx:ro # See config file below

  bumper:
    image: bmartin5692/bumper
    restart: unless-stopped
    networks:
      bumper:

    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Phoenix
      BUMPER_ANNOUNCE_IP: 192.168.1.14 # Insert your IP
      BUMPER_LISTEN: 192.168.1.14
      # BUMPER_DEBUG: "true"
      LOG_TO_STDOUT: "true"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./config:/bumper/data
      - ./certs:/bumper/certs
